DB
HeXA-UNIST/unistMeal-backend pull request #1
Opened 2023-07-10 05:07 UTC by HyunsuYEE

Database is done.

2023-07-10 05:12 UTC, HyunsuYEE commented
데이터베이스만 봐주시면 감사하겠습니다.
controller나 service에 적은 것들은 전부 db도 안짜고 섣불리 짜버린 코드라 무시해주시면 될 것 같아요 :)

2023-07-10 09:26 UTC, SYChoi commented
.idea 폴더나 .iml 파일 등을 깃에 올리지 않도록 .gitignore에 추가하고 지금 올려둔걸 삭제하는게 어떨까...? 굳이 자신의 ide 설정을 모두와 공유할 필요는 없으니까....

2023-07-10 09:29 UTC, SYChoi commented
그리고 리뷰 요청할 때 정말 DB 관련된 새로 작성한 코드만 올려주면 더 좋을거 같음. 굳이 gradlew 같은 프로젝트 세팅하면 자동 세팅되는 파일들은 init commit으로 만들어서 바로 merge 해놔도 상관 없을거라서.

2023-07-11 06:49 UTC, HyunsuYEE commented
gitignore에 DB관련 내용 빼고 전부 추가를 해놨는데, commit하고 push하면 원래 있던 .idea가 사라지지는 않네요.. 
이미 push된걸 삭제하고 다시 push해야할까요?

2023-07-13 01:41 UTC, HyunsuYEE commented
현재 상황 : 
1. relationshipTable을 어떻게 초기화하고, 조회 & 저장을 할 때 어떤 것을 주체로 해야 하는지 몰라서 공부 중
2. excel parsing할 때 day단위로 잘 끊었으나, 중간에 통합 String(예를 들면 공지사항이나 샐러드바?)같은 것들이 끼어 있음. 이런걸 어떤 기준으로 처리할 수 있을지 고민해봐야함.
3. 긱식, 교식, 학식 excel 전부 똑같이 excelImport()라는 서비스의 메서드를 사용하여 excel 하나에 여러 개의 day를 할당시키고, 서비스 내에서 day의 parsing() 메서드를 사용해 엑셀의 내용을 파싱해 Database에 저장하는 방식이다. 이 과정에서 Day나, DayType, MealType, RestaurantType을 넣어야해서 조금 코드가 스파게티가 되었다. 개선할 수 있는 여지가 있으면 의견 주시면 감사하겠음.
4. excel 객체를 각각 AbstractExcel, AbstractDormitoryExcel, DormitorySemesterExcel, DormitoryVacationExcel, ProfessorExcel, StudentExcel이 있는데 별 건 아니고, 유지 보수를 위해 남겨둔 것이다. 
긱식은 방학엔 할랄이 없고, 학기중엔 할랄이 있다. 학식도 방학때는 샐러드바가 없음(식수 부족으로 인한). 그래서 방학 -> 학기 ->방학 이어도 일관성있게 코드를 적용시키기 위해 만들었음. (하지만 파싱이 조금 힘들어서 하드코딩의 가능성이 조금 있다)

2023-07-14 14:22 UTC, junwha0511 requested changes
1. Magic Number 모두 수정해주세요

2. OOP는 객체를 최대한 많이 만들려고 노력하는 것이 목적이 아니라, 기능을 잘 추상화하여 이해하기 쉬운 코드를 만들기 위함이 주 목적입니다.
불필요한 부분에서 객체/메소드를 만드는 것을 줄이고, 내가 짜는 코드의 어느 부분이 서로 분리되어 추상적으로 서로 어떤 기능을 필요로 하고 내부에 은닉되어야 할 기능은 어떤 것이 있는지 깊이 고민한 후에 코드를 짜는 것이 중요합니다.
예를 들어 여기에서는 Abstract* 등의 불필요한 객체를 줄이고, 
- `ExcelParser`: 엑셀에 직접 접근하여 파싱 후 결과를 자신의 내부에 은닉화하여 저장
- `DBWriter`: DB에 접근하여 DTO를 저장 (생략 가능) 
- `ParsingService(혹은 ExcelService)`: 외부로부터 받은 파일을 기반으로 ExcelParser에 일을 전달하고, 은닉화된 결과를 getter를 통해 가져옴. 결과를 DTO에 담아 DBWriter에 전달
이런 느낌으로 명확하게 객체가 수행할 역할을 정의하고 서로 필수적으로 공유해야하는 데이터를 전달하도록 설계해보시면 됩니다.

우선 이 부분 리팩토링 진행하고 추가 리뷰하겠습니다

2023-07-14 14:22 UTC, junwha0511 commented on MealU_HeXA_Project/MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/service/ExcelService.java
> +        if (firstRow.getCell(1).getStringCellValue() == "301동 기숙사식당 식단표") {
magic number 모두 final 변수 혹은 세팅으로 빼주세요

https://drehzr.tistory.com/1136

2023-07-14 14:22 UTC, junwha0511 commented on MealU_HeXA_Project/MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/service/ExcelService.java
> +                // 5, 7, 9, 11.. 와 같은 정수를 0, 1, 2, 3 에 매핑시켜야한다.
여러 줄의 주석은 /* */로 처리해주세요

2023-07-14 14:22 UTC, junwha0511 commented on MealU_HeXA_Project/MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/service/ExcelService.java
> +        Day monday = new Day();
어차피 리스트로 묶을거라면 생성 시부터 리스트로 바로 생성해주세요

2023-07-14 14:22 UTC, junwha0511 commented on MealU_HeXA_Project/MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/service/ExcelService.java
> +        for (int i = startLowNum; i < worksheet.getPhysicalNumberOfRows(); i++) {
getPhysicalNumberOfRows가 O(1)으로 구현되어 있는지 체크 후 사용해주세요 (O(n)이라면 변수로 extract)

2023-07-14 14:22 UTC, junwha0511 commented on MealU_HeXA_Project/MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/service/ExcelService.java
> +                days.get(colNum / 2 - 2)
의미가 존재하는 로직은 메소드로 분리하여 개발자가 함수명을 통해 기능을 이해할 수 있도록해주세요. 위와 같은 주석은 document 주석으로 해당 메소드에 달아주면 됩니다.

2023-07-14 14:22 UTC, junwha0511 commented on MealU_HeXA_Project/MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/service/ExcelService.java
> +            day.parsing(excel.getRestaurantType(), this.mealTableRepository, this.menuRepository); // 레포지토리를 인자로 넘김으로써 save를 day에 위임함.
위임하는 이유가 무엇인가요?

2023-07-14 14:22 UTC, junwha0511 commented on MealU_HeXA_Project/MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/service/ExcelService.java
> +        List<Day> days = excel.getDays();
AbstractExcel에 days 이외에 추가 기능이 없는데 리스트를 인자로 넘기는게 더 깔끔해보입니다

2023-07-14 18:16 UTC, HyunsuYEE commented
조언주신 리펙토링 완료 했습니다. 
1. Day 객체에서의 parse() 메서드를 DBWriter의 save() 메서드로 바꿨습니다.
2. 추상적인 Excel 클래스들을 모두 없애고, ExcelParser 클래스 하나가 모든 역할을 수행합니다. parse() 메서드를 실행하면 자신의 필드에 days와 restaurantType이라는 필드를 초기화합니다.
3. 초기화된 excelParser의 필드(은닉화된 정보)를 DBWriter가 받아 나머지 파싱을 완료하며 각 MealTable & Menu & MealTableAndMenu 의 Repository에 저장합니다. (아직 이부분은 미완성입니다.) 


다만, DBWriter의 로직이 아직 미완성입니다! 
RDB를 DB에 save하는 법 & 한 column을 파싱할 때 Kcal을 기준으로 파싱을 하게 되는데, 
column == day라서 한 day안에 MealTable이 2개(점심 저녁) 혹은 3개(아침 점심 저녁)가 될 수 있습니다.
그래서 코드를 짜는데 조금 스파게티인 느낌이 있네요. MealTable단위로 딱 딱 잘라서 파싱하면 좋겠으나, 메뉴의 갯수가 적은 날이 있을 때는 그 MealTable의 height가 변동이 있기에 일관적으로 짤 수 없다는 느낌을 받습니다. 
어떻게 하면 좋을지 의견 주시면 정말 감사하겠습니다.

2023-07-16 07:22 UTC, junwha0511 requested changes
훨씬 깔끔해졌네요.
리팩토링은 이 부분까지만 반영해주시면 될 것 같습니다.
다음 코멘트에 설계 관련 아이디어 남길게요.

2023-07-16 07:22 UTC, junwha0511 commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +            if (rows.get(DayTypeNum) == "MON") {
daytype method extract 추천 (안해도 상관없음)

2023-07-16 07:22 UTC, junwha0511 commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/Day.java
> +public class Day {
불필요한 클래스

2023-07-16 07:22 UTC, junwha0511 commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +        Row firstRow = worksheet.getRow(1);
firstRow가 아닌, restaurantTypeRow로 정의하고, 해당 상수(1)를 정의하여 사용할 것

2023-07-16 07:22 UTC, junwha0511 commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +        List<Day> days = new ArrayList<>(Arrays.asList(new Day(), new Day(), new Day(), new Day(), new Day(),
stream iterate 혹은 generate로 리팩토링할 것

https://futurecreator.github.io/2018/08/26/java-8-streams/

2023-07-16 07:23 UTC, junwha0511 commented on MealU_HeXA_Project/MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/service/ExcelService.java
> +            day.parsing(excel.getRestaurantType(), this.mealTableRepository, this.menuRepository); // 레포지토리를 인자로 넘김으로써 save를 day에 위임함.
답변 부탁드립니다

2023-07-16 07:23 UTC, junwha0511 commented on MealU_HeXA_Project/MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/service/ExcelService.java
> +                days.get(colNum / 2 - 2)
이 부분 반영 부탁드립니다

2023-07-16 07:23 UTC, junwha0511 commented on MealU_HeXA_Project/MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/service/ExcelService.java
> +        for (int i = startLowNum; i < worksheet.getPhysicalNumberOfRows(); i++) {
확인하셨나요?

2023-07-16 07:24 UTC, junwha0511 commented on MealU_HeXA_Project/MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/service/ExcelService.java
> +                // 5, 7, 9, 11.. 와 같은 정수를 0, 1, 2, 3 에 매핑시켜야한다.
반영 부탁드립니다

2023-07-16 07:25 UTC, junwha0511 commented on MealU_HeXA_Project/MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/service/ExcelService.java
> +        if (firstRow.getCell(1).getStringCellValue() == "301동 기숙사식당 식단표") {
반영 부탁드립니다

2023-07-16 07:38 UTC, junwha0511 commented
> RDB를 DB에 save하는 법 

이 부분 조금 더 자세히 설명 부탁드립니다.

> 한 column을 파싱할 때 Kcal을 기준으로 파싱을 하게 되는데,
column == day라서 한 day안에 MealTable이 2개(점심 저녁) 혹은 3개(아침 점심 저녁)가 될 수 있습니다.
그래서 코드를 짜는데 조금 스파게티인 느낌이 있네요. MealTable단위로 딱 딱 잘라서 파싱하면 좋겠으나, 메뉴의 갯수가 적은 날이 있을 때는 그 MealTable의 height가 변동이 있기에 일관적으로 짤 수 없다는 느낌을 받습니다.


preprocess merged rows (merged row를 공지로 간주하고 모두 white space로 지우기)

key of Mealtable: { Date: Datetime, MealTime: enum { 아침, 점심, 저녁} }


Column을 순회 
    row = 날짜 아래 row
    define mealTimeIdx as 아침
    while row != 해당 칼럼 row의 끝
         set current row as start
         while row != 해당 칼럼 row의 끝 && ! row 내용 has kCal
              row++       
         set current row as end
         => save to mealTime corresponding to mealTimeIdx
         mealTimeIdx++

2023-07-16 13:01 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +        List<Day> days = new ArrayList<>(Arrays.asList(new Day(), new Day(), new Day(), new Day(), new Day(),
Stream.iterate(new Day(), n -> n).limit(7).collect(Collectors.toList()) 로 바꿨습니다!

2023-07-16 13:14 UTC, junwha0511 commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/Day.java
> +public class Day {
Day가 담고 있는 정보가 리스트로 된 Row 목록 밖에 없기 때문에 결국 2차원 리스트를 더 복잡한 구조로 만든 것이 됩니다.
자세히 보시면 Day가 사용되는 부분을 List로 대체해도 아무런 변화가 없다는걸 관측하실 수 있을거에요.

2023-07-23 11:10 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +package HeXA.MealU_HeXA_Project.api.common.parseClass;
패키지 경로에 class가 굳이 들어갈 필요는 없을거 같음... 대신 파싱을 위한 것들을 모아두고 싶은거라면 차라리 parsing이라는 이름으로만 두는게 좋았을듯

2023-07-23 11:11 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +    private static final String Regex = "[0-9]*(,)*[0-9]*(Kcal)";
딱히 아래 함수들이 static인 것도 아니고, 고정된 값이어야 한다는건 final로 표현이 되는데 이 변수들이 static이어야하는 이유는?

2023-07-23 11:17 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +         계산을 해본 결과 1899-12-30 을 기준으로 일수를 세면 45124일이 나오게 된다. (왜 그런지는 모르겠음)
애초에 기준이 1900년 1월 1일을 1일째로 해서 카운트 하고, 그 몇일인지를 실제로 엑셀에 저장하고 있기 때문... 실제 날짜로 가져와서 처리하고 싶다면 string으로 처리해두고 parse하는것도 괜찮지만 이건 원본 데이터를 건드려야하는 것이므로, 원본 데이터가 어떠냐에 따라 처리하는 방법을 달리하고 결과적으로 DB에는 Date가 저장되므로 LocalDate 형식으로 만들어주긴 하는게 좋을 것으로 보임.

2023-07-23 11:19 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +            if (rows.get(DayTypeNum).equals("MON")) {
단순 이런 부분은 switch case 사용하는게 가독성이 더 좋을 것 같고, string 값도 그냥 enum의 value와 같은지 비교해주는게 좋음.

2023-07-23 11:22 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +            if (rows.get(DayTypeNum).equals("MON")) {
이런 단순 변환의 경우에는 심지어 바로 enum에서 찾아올 수도 있음.
DayType.valueOf(rows.get(DayTypeNum))`

2023-07-23 11:30 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +public class DBWriter {
@Component로 그냥 써주면 될듯. 굳이 싱글톤 아닐 이유 없어보임. Bean으로 관리되게 해주자.

2023-07-23 11:30 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +public class DBWriter {
추가로 logger 처리 가능하게 slf4j도 달아주면 좋을거같고.

2023-07-23 11:31 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +                    break;
한줄짜리 코드여도 중괄호 생략하면 코드 읽는데 착각하기 쉬움... 중괄호로 감싸주던지 아니면 아예 같은 줄에 넣던지 둘 중 하나는 하는게 좋아보임.

2023-07-23 11:32 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +                    break;
특히 위에 기숙사 식당 처리하는 부분에서는 중괄호 쓰고 여기는 안해서... 통일성이 없어보임.

2023-07-23 11:36 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +            }
103~107줄 그냥 `mealTypeIdx = restaurantType.equals("기숙사 식당") ? Breakfast : Lunch;` 으로 한줄 요약 되는듯?

2023-07-23 11:38 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +            Pattern pattern = Pattern.compile(Regex);
뭐하고 싶은 Regex인지 몰라서 이 코드 줄의 목적을 모르겠음. Kcal가 있는걸 알고 싶은거니까 kcalRegex 같은 식으로 이름 Regex에 붙여주는게 좋지 않을까?

2023-07-23 11:40 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +public class DBWriter {
아래 코드 보니 repository도 있고 save도 있고 그냥 service였네 여기;;

2023-07-23 11:41 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +public class DBWriter {
Service에 class 이름은 Service로 끝내서 이게 Service라는걸 알게 해주는게 좋음... annotation도 @Service로 처리하고

2023-07-23 11:43 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +                while (r != sizeOfRows && !matcher.matches()) {
안과 밖의 while에 같은 조건 `r != sizeOfRows` 가 들어간 시점에서 애초에 이건 while이 아니라 if로 처리했어야하는 문제...가 아닐까? while 로직이 좀 이상함....

2023-07-23 11:45 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +    private Long StringToFloatAndToLong(String date) {
동사로 함수 이름을 시작해주도록 하자. 예를 들어 transformDateStringToLong 이라던가... 중간에 뭐 했는지는 궁금하지 않음. endToEnd로 이름을 지어줘야함.

2023-07-23 11:46 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +    private LocalDate dateFromMealTableDate(Long date) {
transformDateFromMealTableDays

2023-07-23 11:46 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +    private Long calorieParse(String calories) {
parseCalorie

2023-07-23 11:48 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +    private static final int DormitoryStartRow = 5;
얘들도 굳이 static일 필요는 없어보임. 전역 변수가 없도록 변수 정리를 최대한 해보도록 하자.

2023-07-23 11:49 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +    private static final int MondayColNum = 4;
요런건 요일 enum(DayType) 쪽에 field 변수로 하나 넣어버리고 가져와서 쓰면 좋을듯?

2023-07-23 11:51 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +        this.days = days; // 마지막으로 은닉된 정보(일주일에 대한 식사 정보들)를 excelParser의 필드로 저장한다.
parser의 필드로 저장하면 뭐함;; class는 데이터 저장해두는 DB가 아님. 상수값이나 주입 받아서 쓰는거 이외에 class에 필드 변수로 저장해둘 이유가 전혀 없음.

2023-07-23 11:52 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +    private String excelStringDecodingIntoUtf8(Cell cell) throws UnsupportedEncodingException {
함수 사이에는 한줄씩 비워주자...

2023-07-23 11:56 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +    public ExcelParser(Sheet worksheet) {
worksheet를 주입 받을 필요도 없어보이고, 그게 꼭 class 전체로 올 필요도 없어보이고.... final로 만들어서 쓰는 순간 parser 객체가 sheet 개수만큼 있어야하는데 그거보단 그냥 sheet 몇장이든 처리할 수 있는 parser 하나만 존재하는게 맞지 않을까?

2023-07-23 11:57 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +    public ExcelParser(Sheet worksheet) {
그러려면 worksheet가 그냥 함수에 인자로 들어가거나 setWorksheet 같은 함수로 사용하게 하고, worksheet가 final이 아니게 만들면 됨.

2023-07-23 11:58 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +    private List<List<String>> days;
parse하는 도중에만 유효한 것이므로, 이런것을 그냥 parse 함수 안에 넣어버리고, 함수의 field로 사용하지 말자.

2023-07-23 11:59 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +    private String restaurantType;
얘도 마찬가지로 parse 함수 안에 넣은 걸로 끝내자... 애초에 여기도 놓고 parse 함수 안에 가져오는 구문에서 따로 String으로 선언해서 쓰는 이유가 뭐임...;;

2023-07-23 12:00 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +        String restaurantType = excelStringDecodingIntoUtf8(cell);
private field와 중복되는 변수... 그냥 여기만 쓰자.

2023-07-23 12:00 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +        List<List<String>> days = new ArrayList<>();
얘도 여기만 쓰자. 굳이 field로 만들어서 쓸 이유가 없음.

2023-07-23 12:01 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +        this.days = days; // 마지막으로 은닉된 정보(일주일에 대한 식사 정보들)를 excelParser의 필드로 저장한다.
그냥 return을 애초에 parse된 전체 데이터로 해....

2023-07-23 12:04 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/controller/ExcelController.java
> +        try {
spring은 알아서 throw된 것을 controller가 잡아서 처리해주는 기능이 되어있으므로 service 안에서 예외처리해서 throw 잘 해주도록 하고, 여기서 이렇게 try catch 처리할 필요가 없음... throw 하면 알아서 400대나 500대 에러로 response 돌려보내줌.

2023-07-23 12:05 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/controller/ExcelController.java
> +@Controller
페이지까지 다 만들어주는거임? 그냥 api 처리하는거면 RestController로 해야한다?

2023-07-23 12:06 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/service/ExcelConfig.java
> +public class ExcelConfig {
서비스에 서비스 annotation 안붙이니 여기에 이런게 필요했나보구만... config 떼어내고 그냥 저쪽에 service를 붙이는걸로

2023-07-23 12:07 UTC, SYChoi commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/service/ExcelService.java
> +@Transactional
이러면 여기 서비스는 모두 다 완전 transactional이 되어버리니 readonly=true 옵션 주고, 수정이 있는 함수에만 다시 Transactional 어노테이션을 붙여주자.

2023-07-24 01:14 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +package HeXA.MealU_HeXA_Project.api.common.parseClass;
바꿨습니다!

2023-07-24 01:14 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +    private static final String Regex = "[0-9]*(,)*[0-9]*(Kcal)";
바꿨습니다!

2023-07-24 01:15 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +         계산을 해본 결과 1899-12-30 을 기준으로 일수를 세면 45124일이 나오게 된다. (왜 그런지는 모르겠음)
설계 완료 했습니다!

2023-07-24 01:17 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +public class DBWriter {
설계 완료했습니다..!!

2023-07-24 01:18 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +                    break;
중괄호 추가 했습니다!

2023-07-24 01:18 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +            }
테크닉 추천 감사합니다!! 자바 문법의 부재네요 하핫..

2023-07-24 01:19 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +            Pattern pattern = Pattern.compile(Regex);
변수명 변경 했습니다!

2023-07-24 01:21 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +    private Long StringToFloatAndToLong(String date) {
변경 완료했습니다! 감사합니다 (나머지 이름 변경하는 코멘트도 전부 해결완료 했습니다!)

2023-07-24 01:25 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +        this.days = days; // 마지막으로 은닉된 정보(일주일에 대한 식사 정보들)를 excelParser의 필드로 저장한다.
여기에 질문이 있습니다!
excelParser가 List<List<String>> days 와 String restaurantType이라는 식당 종류 변수를 가지게 되는데 이런 정보를 넘겨주려고 excelParser의 필드에 저장하였는데 parse(Sheet worksheet)라는 메서드로 days를 반환하게 하도록 바꿨습니다! 이 상황에서 restaurantType을 전달해주고 싶으면 어떻게 하면 좋을까요? parse메서드와 restaurantType을 얻는 메서드를 분리시켜 따로 따로 전달하는 것도 방법인가요?

2023-07-24 01:26 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +    private String excelStringDecodingIntoUtf8(Cell cell) throws UnsupportedEncodingException {
네 변경완료했습니다.. 앞으로 커밋 푸쉬할 때 좀 신중히 해야겠네요.. 잔실수가 엄청 많은 것 같습니다

2023-07-24 01:28 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +    public ExcelParser(Sheet worksheet) {
바보같이 worksheet를 final로 주입시켜버렸네요. 변경완료 했습니다! excelParser는 이제 재활용 가능합니다!

2023-07-24 01:28 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +    private List<List<String>> days;
field에서 지우고 parse메서드로 sheet를 받고 List<List<String>>을 반환하도록 바꿨습니다!

2023-07-24 02:10 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +    private String restaurantType;
일단 RestaurantType이라는 변수가 parse할 때 영향을 줌과 동시에 DBWriteService가 데이터를 저장할 떄 excelParser의 필드인 RestaurantType을 가지고 바꾸는 방식을 채택했는데 굳이 필드를 주지 않고 따로따로 정보를 빼내는 방식으로 다시 리펙토링 하겠습니다.
1. parse 메서드 => List<List<String>> days를 반환
2. parseRestaurantType => String restaurantType을 반환 
3. 두 변수를 DBWriteService에 전달 
하는 방식으로 바꾸겟습니다!

2023-07-24 02:11 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +        String restaurantType = excelStringDecodingIntoUtf8(cell);
바보같이 짰네요.. 바꿨습니다!

2023-07-24 02:28 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +        List<List<String>> days = new ArrayList<>();
바꿧습니다! 이제 days라는 필드는 존재하지 않습니다!!

2023-07-24 02:31 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/controller/ExcelController.java
> +        try {
그렇군요.. 감사합니다! 바꿨습니다!

2023-07-24 02:33 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/controller/ExcelController.java
> +@Controller
1. 엑셀을 import하는 페이지 -> DB에 저장 (HomeController)이어서 이 부분은 제가 excel Import하는 페이지를 그냥 간단하게 짜놨어요 테스트 할겸. 그래서 Controller로 놨습니다!
2. 앱에서 요청 -> HomeController -> DB조회 인데 이 부분은 아직 미흡하고 아마 이 부분이 선배가 말씀하신 RestController 써야 할 듯 합니다!

2023-07-24 10:06 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +    private static final int DormitoryStartRow = 5;
동의합니다. static 인 변수 거의 삭제하였습니다! 다음부턴 static 변수는 이 클래스에서 뿐만 아니라 통용으로 사용되는 변수에만 적도록 하겠습니다

2023-07-24 10:07 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/service/ExcelConfig.java
> +public class ExcelConfig {
맞습니다.. config 지우고 DBWriter -> DBWriteService로 바꿨습니다!

2023-07-24 10:07 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/domain/excel/service/ExcelService.java
> +@Transactional
수정하였습니다!

2023-07-24 10:10 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/DBWriter.java
> +                while (r != sizeOfRows && !matcher.matches()) {
수정하였습니다! 저도 조금 이상하다 했는데 조건을 겹쳐 썼네요.. 안, 밖 while이 있다고 하면 안 while문에서 r == sizeOfRows가 되면 break하도록 다시 짰습니다.

2023-07-24 10:11 UTC, HyunsuYEE commented on MealU_HeXA_Project/src/main/java/HeXA/MealU_HeXA_Project/api/common/parseClass/ExcelParser.java
> +    private static final int MondayColNum = 4;
변수들을 옮기고 static import 해서 가져와서 쓰도록 바꿨습니다!

2023-09-08 15:06 UTC, merged